### ISSUE TITLE
about training

### ISSUE THREAD

**Issue by mychina75** [leohsuofnthu/Tensorflow-YOLACT#2]
Hi,
looks like the code is not ready for training yet. 
following is the error report. Am I made some mistake?

#############
2019-06-27 11:11:32.033071: W tensorflow/core/framework/op_kernel.cc:1655] OP_REQUIRES failed at gather_nd_op.cc:47 : Invalid argument: indices[313] = [7, 19118] does not index into param shape [8,4,4]
Traceback (most recent call last):
  File "/pycharm-community-2018.2.1/helpers/pydev/pydevd.py", line 1664, in <module>
    main()
  File "/pycharm-community-2018.2.1/helpers/pydev/pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/pycharm-community-2018.2.1/helpers/pydev/pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/pycharm-community-2018.2.1/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "./Tensorflow-YOLACT/train.py", line 229, in <module>
    app.run(main)
  File "/anaconda3/lib/python3.6/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/anaconda3/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "./Tensorflow-YOLACT/train.py", line 150, in main
    loc_loss, conf_loss, mask_loss, seg_loss = train_step(model, criterion, train_loss, optimizer, image, labels)
  File "./Tensorflow-YOLACT/train.py", line 56, in train_step
    loc_loss, conf_loss, mask_loss, seg_loss, total_loss = loss_fn(output, labels, 91)
  File "./Tensorflow-YOLACT/loss/loss_yolact.py", line 46, in __call__
    loc_loss = self._loss_location(pred_offset, box_targets, positiveness) * self._loss_weight_box
  **File "./Tensorflow-YOLACT/loss/loss_yolact.py", line 67, in _loss_location
    gt_offset = tf.gather_nd(gt_offset, pos_indices[:, :-1])**
  File "/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/util/dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/ops/array_ops.py", line 4436, in gather_nd_v2
    return gather_nd(params, indices, name=name, batch_dims=batch_dims)
  File "/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/util/dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/ops/array_ops.py", line 4428, in gather_nd
    return gen_array_ops.gather_nd(params, indices, name=name)
  File "/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/ops/gen_array_ops.py", line 3591, in gather_nd
    _ops.raise_from_not_ok_status(e, name)
  File "/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 6606, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: **indices[313] = [7, 19118] does not index into param shape [8,4,4] [Op:GatherNd]**

**Comment by leohsuofnthu** [comment]
Hi,
  Thanks for the interest in this project, this project is still a prototype. I just start a full check compared to the original author s code and result now. I will try to provide a correct version ASAP. Probably next week. :)

**Comment by mychina75** [comment]
Great! 
I will keep tracking your updates. thanks~

**Comment by leohsuofnthu** [comment]
Hi, I already finish the part for training, and also provide the usage in Readme. Thx
