### ISSUE TITLE
train coco dataset error

### ISSUE THREAD

**Issue by lincong666** [leohsuofnthu/Tensorflow-YOLACT#20]
OP_REQUIRES failed at iterator_ops.cc:929 : Invalid argument: {{function_node __inference_Dataset_map_<class 'data.yolact_parser.Parser'>_1307}} ConcatOp : Ranks of all input tensors should match: shape[0] = [138,138] vs. shape[1] = [99,138,138]
	 [[{{node parser/concat}}]]
Traceback (most recent call last):
  File "train.py", line 269, in <module>
    app.run(main)
  File "/home/bigdata/anaconda3/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/bigdata/anaconda3/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "train.py", line 166, in main
    for image, labels in train_dataset:
  File "/home/bigdata/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/data/ops/iterator_ops.py", line 622, in __next__
    return self.next()
  File "/home/bigdata/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/data/ops/iterator_ops.py", line 666, in next
    return self._next_internal()
  File "/home/bigdata/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/data/ops/iterator_ops.py", line 651, in _next_internal
    output_shapes=self._flat_output_shapes)
  File "/home/bigdata/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/ops/gen_dataset_ops.py", line 2691, in iterator_get_next_sync
    _six.raise_from(_core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: {{function_node __inference_Dataset_map_<class 'data.yolact_parser.Parser'>_1307}} ConcatOp : Ranks of all input tensors should match: shape[0] = [138,138] vs. shape[1] = [99,138,138]
	 [[{{node parser/concat}}]] [Op:IteratorGetNextSync]

**Comment by lincong666** [comment]
Does anyone have this error？
